theme: minima
title: Kelvya Thais
author: kelvya
email: kelvyat@hotmail.com
description: blog sobre os estudos de engenharia de software

# social links
twitter_username: eusoukelvya
github_username:  kelvya
show_excerpts: true
